= Movies Example Application

image:https://github.com/neo4j-examples/movies-java-spring-data-neo4j/workflows/build/badge.svg[Build Status,link=https://github.com/neo4j-examples/movies-java-spring-data-neo4j/actions]

How to use Spring Boot, Spring Data, and Neo4j together.

Spring Data Neo4j enables convenient integration of Neo4j in your Spring-based application..
It provides object-graph mapping (OGM) functionality and other features common to the Spring Data projects.

[NOTE]
This project uses Spring Data Neo4j 6.
The example project is described in detail on the https://neo4j.com/developer/example-project/[Neo4j Developer Site]

The project uses Java 11.

== The Stack

These are the components of our Web Application:

* Application Type:         Spring-Boot Java Web Application
* Web framework:            Spring-Boot enabled Spring-WebMVC
* Persistence Access:       Spring-Data-Neo4j 6.x
* Database:                 Neo4j-Server 3.5, or 4.x with multi-database
* Frontend:                 jquery, bootstrap, http://d3js.org/[d3.js]

Provision a database quickly with https://sandbox.neo4j.com/?usecase=movies[Neo4j Sandbox] or https://neo4j.com/cloud/aura/[Neo4j Aura].

== Configuration options - public API with data

[%header,cols=2*]
|===
|Environment variable name
|Default value (or N/A)

|PORT
|8080

|NEO4J_URI
|neo4j+s://demo.neo4jlabs.com

|NEO4J_USER
|movies

|NEO4J_PASSWORD
|movies

|NEO4J_DATABASE
|movies

|NEO4J_VERSION
|4
|===

This will use a public API, if you have your own database running just connect to that instead.